### ISSUE TITLE
Could not parse version: line is '// TypeScript Version: 2.6'

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/dtslint#112]
I'm trying to lint the React types in DefinitelyTyped, but I get:

```
❯ npm run lint react

> definitely-typed@0.0.1 lint /Users/OliverJAsh/Development/DefinitelyTyped
> dtslint types "react"

Error: Could not parse version: line is '// TypeScript Version: 2.6'
    at Object.parseTypeScriptVersionLine (/Users/OliverJAsh/Development/DefinitelyTyped/node_modules/definitelytyped-header-parser/index.js:180:15)
    at getTypeScriptVersion (/Users/OliverJAsh/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:90:44)
    at /Users/OliverJAsh/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:66:28
    at Generator.next (<anonymous>)
    at fulfilled (/Users/OliverJAsh/Development/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

This is after a fresh install of Node modules.

**Comment by andy-ms** [comment]
Works for me with a fresh install -- are you sure you don't have a `package-lock` holding you back? Note the update would not be of dtslint but of https://github.com/Microsoft/definitelytyped-header-parser .

**Comment by OliverJAsh** [comment]
Ah, I hadn't cleared my `yarn.lock`. Apologies!
