### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by elderapo** [Microsoft/dtslint#123]
I am getting these errors. Not sure if these are bugs or I am doing something wrong. There are no interfaces without "I" at begining as some error says.

```
node: v8.11.2
yarn: 1.5.1
dtslint: 0.3.0
os: windows
```
https://ci.appveyor.com/project/elderapo/typed-event-emitter/build/1.0.1
```
$ dtslint test/types --onlyTestTsNext
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.0...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.1...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.2...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.3...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.4...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.5...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.6...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.7...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\2.8...
Installed!
Installing to C:\projects\typed-event-emitter\node_modules\dtslint\typescript-installs\next...
Installed!
The 'no-empty-interface' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEmptyInterfaceRule.js:50:26)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15331:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEmptyInterfaceRule.js:54:19)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15329:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEmptyInterfaceRule.js:54:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEmptyInterfaceRule.js:48:15)
The 'no-eval' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEvalRule.js:50:29)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15276:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEvalRule.js:53:19)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15333:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEvalRule.js:53:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noEvalRule.js:48:15)
The 'no-object-literal-type-assertion' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noObjectLiteralTypeAssertionRule.js:49:64)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15333:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noObjectLiteralTypeAssertionRule.js:53:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noObjectLiteralTypeAssertionRule.js:48:15)
    at Rule.AbstractRule.applyWithFunction (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\language\rule\abstractRule.js:39:9)
    at Rule.apply (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\noObjectLiteralTypeAssertionRule.js:29:21)
    at Linter.applyRule (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\linter.js:197:29)
The 'radix' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\radixRule.js:49:64)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15276:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\radixRule.js:61:19)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15333:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\radixRule.js:61:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\radixRule.js:48:15)
The 'prefer-const' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (C:\projects\typed-event-emitter\node_modules\tsutils\typeguard\node.js:306:17)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferConstRule.js:159:27)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15276:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferConstRule.js:172:27)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15333:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferConstRule.js:167:20)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
The 'callable-types' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\callableTypesRule.js:52:29)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15331:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\callableTypesRule.js:64:19)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15329:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\callableTypesRule.js:64:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\callableTypesRule.js:50:15)
The 'prefer-object-spread' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferObjectSpreadRule.js:51:64)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15276:21)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferObjectSpreadRule.js:71:19)
    at visitNode (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15089:24)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15333:24)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferObjectSpreadRule.js:71:19)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at walk (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferObjectSpreadRule.js:50:15)
The 'prefer-while' rule threw an error in 'C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'pos' of undefined
    at Rule.createFailure (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferWhileRule.js:46:34)
    at cb (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferWhileRule.js:34:37)
    at visitNodes (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15098:30)
    at Object.forEachChild (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\typescript\lib\typescript.js:15324:24)
    at Rule.apply (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\rules\preferWhileRule.js:38:12)
    at Linter.applyRule (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\linter.js:197:29)
    at C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\linter.js:139:85
    at Object.flatMap (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\utils.js:151:29)
    at Linter.getAllFailures (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\linter.js:139:32)
    at Linter.lint (C:\projects\typed-event-emitter\node_modules\dtslint\node_modules\tslint\lib\linter.js:99:33)
Error: C:/projects/typed-event-emitter/test/types/typed-event-emitter.ts:34:7
ERROR: 34:7  interface-name  interface name must start with a capitalized I
    at C:\projects\typed-event-emitter\node_modules\dtslint\bin\index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\projects\typed-event-emitter\node_modules\dtslint\bin\index.js:5:58)
    at <anonymous>
error An unexpected error occurred: "Command failed.
Exit code: 1
```

```
node: v9.5.0
yarn: 1.6.0
dtslint: 0.3.0
os: ubuntu 14.04
```

```
yarn run v1.6.0
$ dtslint test/types --onlyTestTsNext
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.0...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.1...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.2...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.3...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.4...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.5...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.6...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.7...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/2.8...

Installed!
Installing to /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/typescript-installs/next...

Installed!
The 'no-empty-interface' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEmptyInterfaceRule.js:50:26)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15331:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEmptyInterfaceRule.js:54:19)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15329:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEmptyInterfaceRule.js:54:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEmptyInterfaceRule.js:48:15)
The 'no-eval' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEvalRule.js:50:29)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15276:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEvalRule.js:53:19)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15333:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEvalRule.js:53:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noEvalRule.js:48:15)
The 'no-object-literal-type-assertion' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:49:64)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15333:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:53:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:48:15)
    at Rule.AbstractRule.applyWithFunction (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/noObjectLiteralTypeAssertionRule.js:29:21)
    at Linter.applyRule (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/linter.js:197:29)
The 'radix' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/radixRule.js:49:64)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15276:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/radixRule.js:61:19)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15333:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/radixRule.js:61:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/radixRule.js:48:15)
The 'prefer-const' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (/home/elderapo/nodejs/typed-event-emitter/node_modules/tsutils/typeguard/node.js:306:17)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferConstRule.js:159:27)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15276:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferConstRule.js:172:27)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15333:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferConstRule.js:167:20)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
The 'callable-types' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/callableTypesRule.js:52:29)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15331:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/callableTypesRule.js:64:19)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15329:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/callableTypesRule.js:64:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/callableTypesRule.js:50:15)
The 'prefer-object-spread' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'length' of undefined
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferObjectSpreadRule.js:51:64)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15276:21)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferObjectSpreadRule.js:71:19)
    at visitNode (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15089:24)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15333:24)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferObjectSpreadRule.js:71:19)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at walk (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferObjectSpreadRule.js:50:15)
The 'prefer-while' rule threw an error in '/home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts':
TypeError: Cannot read property 'pos' of undefined
    at Rule.createFailure (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferWhileRule.js:46:34)
    at cb (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferWhileRule.js:34:37)
    at visitNodes (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15098:30)
    at Object.forEachChild (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/typescript/lib/typescript.js:15324:24)
    at Rule.apply (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/rules/preferWhileRule.js:38:12)
    at Linter.applyRule (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/linter.js:197:29)
    at /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/linter.js:139:85
    at Object.flatMap (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/utils.js:151:29)
    at Linter.getAllFailures (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/linter.js:139:32)
    at Linter.lint (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/node_modules/tslint/lib/linter.js:99:33)
Error: /home/elderapo/nodejs/typed-event-emitter/test/types/typed-event-emitter.ts:34:7
ERROR: 34:7  interface-name  interface name must start with a capitalized I

    at /home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/bin/index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/elderapo/nodejs/typed-event-emitter/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by elderapo** [comment]
I found the cause of this issue. Everything works just fine if `npm install` is used instead of `yarn install` (yarn 1.6.0/1.7.0). Also it seems to work with very ancient version of yarn `0.27.0`.

I am not sure if this is bug in yarn or dtslint.

**Comment by NikitaIT** [comment]
This is resolved here, this is not a dtslint problem:
https://github.com/microsoft/TypeScript/issues/21607#issuecomment-363988238

I think it can be closed.
