### ISSUE TITLE
Syntax error when using TypeScript 3

### ISSUE THREAD

**Issue by nickmccurdy** [Microsoft/dtslint#137]
```
// TypeScript Version: 3.0

Error: Could not parse version: line is '// TypeScript Version: 3.0'
    at Object.parseTypeScriptVersionLine (/usr/local/lib/node_modules/dtslint/node_modules/definitelytyped-header-parser/index.js:181:15)
    at getTypeScriptVersion (/usr/local/lib/node_modules/dtslint/bin/index.js:125:44)
    at /usr/local/lib/node_modules/dtslint/bin/index.js:93:28
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/dtslint/bin/index.js:5:58)
```

**Comment by Gregroam** [comment]
Bump!

**Comment by m93a** [comment]
This can be fixed by Microsoft/definitelytyped-header-parser#15 but it doesn't seem to get any attention from the maintainers.
