### ISSUE TITLE
Error when running linter on DT repo

### ISSUE THREAD

**Issue by SimonSchick** [Microsoft/dtslint#148]
```
➜  joi git:(master) ✗ npm run lint joi

> definitely-typed@0.0.3 lint /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped
> dtslint types "joi"

Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.0...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.1...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.2...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.3...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.4...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.5...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.6...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.7...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.8...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/2.9...

Installed!
Installing to /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/typescript-installs/next...

Installed!
TypeError: definitelytyped_header_parser_1.TypeScriptVersion.isRedirectable is not a function
    at /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:148:102
    at Generator.next (<anonymous>)
    at /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:4:12)
    at testTypesVersion (/Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:143:12)
    at /Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:128:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/v-sischi/Projects/misc/vendor/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
```

```
➜  joi git:(master) ✗ cat ../../node_modules/dtslint/package.json | jq .version
"0.3.0"
```

What can I do to avoid this issue? :/

**Comment by andy-ms** [comment]
Seems like a version mismatch? `isRedirectable` was added in a recent version of `definitelytyped-header-parser`, so you must have an old version installed. Maybe you just need to refresh `node_modules`?

**Comment by SimonSchick** [comment]
I already did that, I will try to clear my local module cache.

**Comment by SimonSchick** [comment]
Ok, cleared cached and re-install twice, works now.
Must've been some sort of glitch with the installation, probably related to the fact that you are currently relying on a github package install.

You might want to look into that.
