### ISSUE TITLE
Unable to add Typescript 3.1 via typesVersions

### ISSUE THREAD

**Issue by surgeboris** [microsoft/dtslint#160]
I need some of TS 3.1 features for the `react-redux` type definitions on DefinitelyTyped, so [I tried to set it up](https://github.com/surgeboris/DefinitelyTyped/commit/b413d8d7731ee62de6ac7e991947f2a553538bbb) exactly in the same way as [it was done for `es6-shim` module](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30148).

However when I run `npx dtslint types/react-redux` I'm getting the following error:
```
Error: /DefinitelyTyped/types/react-redux/ts3.1/index.d.ts:1:1
ERROR: 1:1  expect  Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file '/DefinitelyTyped/types/react-redux/ts3.1/index.d.ts' present in 3.3.0-dev.20181122, but did not find it in ts@3.0.
    at /DefinitelyTyped/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
```
which [seems to be introduced recently](https://github.com/Microsoft/dtslint/commit/0205372bd88e0754a0c52d20505c9083e5504689).

I'm not sure if it's me doing something wrong, or dtslint not yet ready to fully support `typesVersions` usage, but I decided to report this issue as error itself suggests that it might be bug.

**Comment by leonard-thieu** [comment]
This still happens when running `npm run lint` but not with `npm test`. See https://github.com/leonard-thieu/DefinitelyTyped/pull/19 (https://github.com/leonard-thieu/DefinitelyTyped/pull/19/commits/d4b48dda9438f7a7a1c5d8899bc4fc2779d29792) where the build fails with (unrelated) reason:

```
Error: /home/travis/build/leonard-thieu/DefinitelyTyped/types/jquery/test/longdesc-tests.ts:1300:26
ERROR: 1300:26  no-unnecessary-type-assertion  This assertion is unnecessary since it does not change the type of the expression.
```

versus running `npm run lint jquery` locally:

```
Error: S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/test/longdesc-tests.ts:1300:26
ERROR: 1300:26  no-unnecessary-type-assertion  This assertion is unnecessary since it does not change the type of the expression.

S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/JQuery.d.ts:1:1
ERROR: 1:1      expect                         Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/JQuery.d.ts' present in 3.3.0-dev.20181222, but did not find it in ts@3.0.

S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/JQueryStatic.d.ts:1:1
ERROR: 1:1      expect                         Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/JQueryStatic.d.ts' present in 3.3.0-dev.20181222, but did not find it in ts@3.0.

S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/index.d.ts:1:1
ERROR: 1:1      expect                         Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/index.d.ts' present in 3.3.0-dev.20181222, but did not find it in ts@3.0.

S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/legacy.d.ts:1:1
ERROR: 1:1      expect                         Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/legacy.d.ts' present in 3.3.0-dev.20181222, but did not find it in ts@3.0.

S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/misc.d.ts:1:1
ERROR: 1:1      expect                         Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'S:/Projects/_GitHub/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/misc.d.ts' present in 3.3.0-dev.20181222, but did not find it in ts@3.0.
```

**Comment by leonard-thieu** [comment]
I take that back. This seems to happen when I run `npm test` locally too.

I've run `npm cache clean --force`, deleted `node_modules`, and run `git clean -xdf` until clean but I still get the errors.
