### ISSUE TITLE
error when running lint on package (SyntaxError: Unexpected token } in JSON)

### ISSUE THREAD

**Issue by chrisdrackett** [microsoft/dtslint#241]
I'm getting the following error when trying to test updates to a package (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37415)

I have no idea what JSON it is referring to...

```
SyntaxError: Unexpected token } in JSON at position 82
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/cwd/src/DefinitelyTyped/node_modules/dtslint/bin/util.js:19:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cwd/src/DefinitelyTyped/node_modules/dtslint/bin/util.js:4:58)
```

**Comment by iamandrewluca** [comment]
Also getting this error, when working on this DefinitelyTyped/DefinitelyTyped/pull/40982

```
npm install
npm test
```
