### ISSUE TITLE
ENOENT: no such file or directory, mkdir '/home/USER/.dts/perf'

### ISSUE THREAD

**Issue by albertogasparin** [microsoft/dtslint#246]
Running this command on Circle CI:

```
dtslint --expectOnly --localTs node_modules/typescript/lib ./types
```

I get the following error:

```
The 'expect' rule threw an error in '/home/circleci/repo/types/index.d.ts':
Error: ENOENT: no such file or directory, mkdir '/home/circleci/.dts/perf'
    at Object.mkdirSync (fs.js:750:3)
    at getFailures (/home/circleci/repo/node_modules/dtslint/bin/rules/expectRule.js:35:30)
    at Rule.applyWithProgram (/home/circleci/repo/node_modules/dtslint/bin/rules/expectRule.js:42:29)
    at Linter.applyRule (/home/circleci/repo/node_modules/tslint/lib/linter.js:211:29)
    at /home/circleci/repo/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/home/circleci/repo/node_modules/tslint/lib/utils.js:160:29)
    at Linter.getAllFailures (/home/circleci/repo/node_modules/tslint/lib/linter.js:155:32)
    at Linter.lint (/home/circleci/repo/node_modules/tslint/lib/linter.js:110:33)
    at Object.<anonymous> (/home/circleci/repo/node_modules/dtslint/bin/lint.js:51:24)
    at Generator.next (<anonymous>)
```

Interestingly it looks like the command does not actually fail but I'm not sure whenever all tests run properly.

Version: `0.9.1`
CI image: `circleci/node:10.12`

**Comment by albertogasparin** [comment]
Also, out of curiosity, why is it writing data into `/home/USER/.dts` in the first place?

**Comment by albertogasparin** [comment]
Thanks! Just a suggestion: for people that use `--localTs` you could set the cache/perf dir inside `node_modules` or in a tmp folder, as I'm a bit concerned having those caches persisting in the same place across projects.
