### ISSUE TITLE
`extends` in `tsconfig.json` not recognised

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/dtslint#254]
I have the following `tsconfig.json` in my tests folder:

```json
{
  "extends": "../tsconfig-base.json",
  "include": [
    "../shared/typings/*",
    "**/*"
  ]
}
```

When I try to use dtslint, it errors with:

```
TypeError: Cannot use 'in' operator to search for 'lib' in undefined
    at Object.<anonymous> (/Users/oliverash/Development/unsplash-web/node_modules/dtslint/bin/checks.js:103:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oliverash/Development/unsplash-web/node_modules/dtslint/bin/checks.js:4:58)
```

If I define an empty `compilerOptions`, it then errors with:

```
Error: Must specify "lib", usually to `"lib": ["es6"]` or `"lib": ["es6", "dom"]`.
    at Object.<anonymous> (/Users/oliverash/Development/unsplash-web/node_modules/dtslint/bin/checks.js:103:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oliverash/Development/unsplash-web/node_modules/dtslint/bin/checks.js:4:58)
```

Even though there is a `lib` option specified inside the extend config (`../tsconfig-base.json`).

**Comment by OliverJAsh** [comment]
Hey @sandersn, sorry to pester but do you consider this a bug or working as intended?

**Comment by sandersn** [comment]
bug + help wanted: definitely typed doesn't need this but there's no reason it shouldn't work

**Comment by StreetStrider** [comment]
@OliverJAsh looks like a hack. I think, TypeScript language api should be used for this kind of tasks by itself. Something like `ts.createProgram` (I'm not sure). There must be specific method for that task.
