### ISSUE TITLE
Cannot find module '/Users/JounQin/.dts/typescript-installs/next/node_modules/typescript'

### ISSUE THREAD

**Issue by JounQin** [microsoft/dtslint#267]
I tried deleting `yarn.lock` and install all dependencies like https://github.com/microsoft/dtslint#faq but it didn't work.

```sh
Error: Command failed: yarn dtslint --expectOnly packages/svelte
Error: Cannot find module '/Users/JounQin/.dts/typescript-installs/next/node_modules/typescript'
Require stack:
- /Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/lint.js
- /Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at testDependencies (/Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/lint.js:63:16)
    at Object.<anonymous> (/Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/lint.js:25:28)
    at Generator.next (<anonymous>)
    at /Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/lint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/JounQin/Workspaces/GitHub/types/node_modules/dtslint/bin/lint.js:4:12)
error Command failed with exit code 1.
```

reproduction: https://github.com/rx-ts/types/runs/412739812?check_suite_focus=true#step:6:23

repo: https://github.com/rx-ts/types

command: `yarn test`

**Comment by jablko** [comment]
Could this have been due to concurrent dtslint invocations trampling each other installing TypeScript versions? https://github.com/rx-ts/types/blob/544b5fdcb44a2c6c63ba9391752bef8affad4711/scripts/dtslint.ts#L15

I realize this comes a bit late: that `dtslint.ts` script [has been removed](https://github.com/rx-ts/types/commit/4da2bf7e1f185b0889bf68bb5158d1c2277e246a#diff-bbe39ff41112c073a1614fe90147d886f06874d08628df797b09ab0de7a445e7). I just ran into [a similar issue](https://github.com/mdx-js/mdx/pull/1622#discussion_r697920090) with `lerna run` that I (think) I solved with [`lerna --concurrency 1 run`](https://github.com/lerna/lerna/blob/main/core/global-options/README.md#--concurrency).
