### ISSUE TITLE
no-redundant-jsdoc-2 rule threw an error in [...]  Unexpected tag kind: JSDocPrivateTag

### ISSUE THREAD

**Issue by BigsonLvrocha** [microsoft/dtslint#278]
steps to reproduce:
- clone https://github.com/DefinitelyTyped/DefinitelyTyped
- run `yarn install`
- run `yarn lint relay-runtime`
trace:
```
The 'no-redundant-jsdoc-2' rule threw an error in 'DefinitelyTyped/types/relay-runtime/index.d.ts':
Error: Unexpected tag kind: JSDocPrivateTag
    at checkTag (DefinitelyTyped/node_modules/dtslint/bin/rules/noRedundantJsdoc2Rule.js:102:23)
    at cb (DefinitelyTyped/node_modules/dtslint/bin/rules/noRedundantJsdoc2Rule.js:51:25)
    at Array.forEach (<anonymous>)
    at walk (DefinitelyTyped/node_modules/dtslint/bin/rules/noRedundantJsdoc2Rule.js:40:34)
    at Rule.AbstractRule.applyWithFunction (DefinitelyTyped/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (DefinitelyTyped/node_modules/dtslint/bin/rules/noRedundantJsdoc2Rule.js:18:25)
    at Linter.applyRule (DefinitelyTyped/node_modules/tslint/lib/linter.js:214:29)
    at DefinitelyTyped/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (DefinitelyTyped/node_modules/tslint/lib/utils.js:160:29)
    at Linter.getAllFailures (DefinitelyTyped/node_modules/tslint/lib/linter.js:155:32)
```

**Comment by ExE-Boss** [comment]
Duplicate of <https://github.com/microsoft/dtslint/issues/281>
