### ISSUE TITLE
Feature request: Disable testing against `@next`

### ISSUE THREAD

**Issue by crutchcorn** [microsoft/dtslint#288]
I'm currently working on adding `dtslint` support to @PlopJS. However, I'm getting errors from upstream `lib` issues:

```
Error: Errors in typescript@4.0 for external dependencies:
../../../../.dts/typescript-installs/4.0/node_modules/typescript/lib/lib.es2015.iterable.d.ts(41,6): error TS2300: Duplicate identifier 'IteratorResult'.
../node_modules/@types/node/index.d.ts(179,11): error TS2300: Duplicate identifier 'IteratorResult'.

    at C:\Users\crutchcorn\git\Plop\node-plop\node_modules\dtslint\bin\index.js:196:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\crutchcorn\git\Plop\node-plop\node_modules\dtslint\bin\index.js:6:58)
```

This isn't the first time that testing against `next` has broken typings for me. For some projects, I want to _enable_ testing against next, while other projects I'd like to disable that functionality altogether. I understand that I can restrict to a local TS version, but then I'm limiting testing against only one version of TS, which isn't ideal when trying to test against a myriad of versions to ensure capability.

I'd love for an option to disable testing unstable releases of TS while remaining with the power to test the range of stable releases

**Comment by IanVS** [comment]
I've also noticed that even though right now it says it's testing Typescript 4.5, it's actually installing and testing `4.7.0-dev.20220216`, which is super confusing, if nothing else.
